name: Free Cloudflare VPS

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest # Đổi thành ubuntu-latest nếu muốn dùng Linux
    timeout-minutes: 360 # Giới hạn tối đa 6 tiếng (360 phút)

    steps:
    - name: Tải và cài đặt Cloudflare Tunnel x64
      shell: powershell
      run: |
        # Tải file cài đặt msi chính thức từ Cloudflare
        Invoke-WebRequest -Uri "https://github.com" -OutFile "cloudflared.msi"
        
        # Chạy cài đặt ẩn dưới nền hệ thống
        Start-Process msiexec.exe -ArgumentList '/i cloudflared.msi /qn /norestart' -Wait
        
    #- name: Kích hoạt Remote Desktop (Chỉ áp dụng cho Windows)
     # shell: cmd
      #run: |
        #reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        #net user runneradmin MyPassword123! /add
        #net localgroup administrators runneradmin /add
    - name: Kích hoạt Remote Desktop và Đổi mật khẩu
      shell: cmd
      run: |
        reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        net user runneradmin Anhmanh2k@
        
    - name: Tạo đường hầm kết nối công khai
      shell: cmd
      run: |
        .\cloudflared.exe tunnel --url rdp://localhost:3389
        
